export const START_LOADING = 'MATERIAL_START_LOADING';

export const STOP_LOADING = 'MATERIAL_STOP_LOADING';

export const SET_ERROR = 'MATERIAL_SET_ERROR';

export const UNSET_ERROR = 'MATERIAL_UNSET_ERROR';

export const SET_MATERIAL = 'MATERIAL_SET_MATERIAL';

export const UNSET_MATERIAL = 'MATERIAL_UNSET_MATERIAL';
