export const START_LOADING = 'MATERIALS_START_LOADING';

export const STOP_LOADING = 'MATERIALS_STOP_LOADING';

export const SET_ERROR = 'MATERIALS_SET_ERROR';

export const UNSET_ERROR = 'MATERIALS_UNSET_ERROR';

export const EXPAND_MATERIALS = 'MATERIALS_EXPAND_MATERIALS';

export const CLEAR_MATERIALS = 'MATERIALS_CLEAR_MATERIALS';
